### ISSUE TITLE
column "match source"

### ISSUE THREAD

**Issue by mderrien95** [Zquinlan/ecoNet#6]
Hello, 
Thank you very much for creating this usefull tool.
However I am wondering: When I open the conciseConsensus created file, in the column "match source", some cells are filled with "in silico" but no information is given about the chemical classes / pathway of the corresponded feature. Is it normal ?
Thanks, 

Marie

**Comment by Zquinlan** [comment]
Hi Marie!

I’m stoked you’re liking the tool!

That hasn’t happened in any of my test datasets. Typically if there is not class/pathway info available then the matchSource column will also be NA. This could be the result of differences in the in silico tool you are using (eg. Instead of being NA for unknown pathways it is an empty character value “”). Are you using SIRIUS/CANOPUS or some other In silico tool? I will try to see if I can replicate the bug on my end.

-Zaq :)

_________________________________
Zachary A. Quinlan, Ph.D.
NSF-OCE Postdoctoral Research Fellow
Hawai’i Institute of Marine Biology  |  University of Hawai’i
Phone 720-937-8862
***@***.***

**Comment by mderrien95** [comment]
Thank Zaq for your quick answer.
Yes, I use SIRIUS and I loaded the canopus.compound.summary.tsv from it.
I re-exported it from SIRIUS and now, I have this kind of error... I don't know why... 

![Screenshot 2023-12-14 183627_errorCONCISE](https://github.com/Zquinlan/conCISE/assets/121160925/2fe6c16c-b17b-4e78-995d-767722efd0aa)

Thank you in advances,

Marie

**Comment by Zquinlan** [comment]
Hmm. So from your first run (when it ran) in the cases where CONCISE lists a match source as in silico but has an empty consensus, can you check the Canopus summary file to make sure that there is indeed no information provided. If you are willing to share the original Canopus summary and concise export with me, I can also do some sleuthing to figure out what is going on.

The UTF-8 error is caused when there is an encoding error when it is trying to read the .tsv. Why that is occurring from a SIRIUS export, I do not know. I’ll run SIRIUS on my end again to see if I similarly get this encoding error.

**Comment by mderrien95** [comment]
Hi Zaq, 
I am wondering if it's finally the match source could be related to the classyfire classification and not to the NPC classification (see the screenshot where I put the sirius results near to the conciseconsensus file. For example, for the feature 176 I haven't results for NPC). Other thing why I think that is beacause of the "subclass" in the "concise consensus level" column.
Maybe you could try with a one of your run and see if you have the same case like me.

![Screenshot 2023-12-15 135444_concise_sirius](https://github.com/Zquinlan/conCISE/assets/121160925/9ab2bdd4-ec3b-4abd-9d4d-8800db6c3e4f)

For the second problem, I re-imported the summary from sirius and the concise run worked. 
The difference with the first time, it that I didn't open the canopus summary file in excel (and save it in csv UTF8) before to load it in CONCISE.
