### ISSUE TITLE
Problem with Classyfire Ontologies

### ISSUE THREAD

**Issue by AndreaCa96** [Zquinlan/ecoNet#7]
Hello,

When I try to uncheck NPC classifier in order to obtain ClassyFire Ontologies from Sirius, I receive this error message:

pandas\io\json\_json.py:878: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
pandas\io\json\_json.py:951: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
pandas\io\json\_json.py:878: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
pandas\io\json\_json.py:951: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
Exception in thread Thread-1 (runWorkFlow):
Traceback (most recent call last):
  File "threading.py", line 1038, in _bootstrap_inner
  File "threading.py", line 975, in run
  File "workflowMain.py", line 58, in runWorkFlow
TypeError: 'getJob' object is not subscriptable

If I try to start with NPC, I have no problem and the result is okay. How can I obtain the classification with ClassyFire Ontologies?

Thanks in advance!
Thanks in advance!

**Comment by Zquinlan** [comment]
What framework are you using (GUI, command line tool, or online interface) and what operating system?

**Comment by AndreaCa96** [comment]
I'm use GUI on windows 11

**Comment by Zquinlan** [comment]
Try [this version](https://github.com/Zquinlan/conCISE/releases/download/v1.21/conCISEGui.exe). I think when I made some fixes in the past few months those did not get redistributed to the windows GUI. I just remade the executable file so hopefully it works not but let me know if it doesn't and I will take a deeper look!

**Comment by AndreaCa96** [comment]
Not yet :\

pandas\io\json\_json.py:889: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
pandas\io\json\_json.py:962: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
pandas\io\json\_json.py:889: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
pandas\io\json\_json.py:962: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
pandas\core\internals\blocks.py:904: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
Exception in thread Thread-4 (runWorkFlow):
Traceback (most recent call last):
  File "threading.py", line 1045, in _bootstrap_inner
  File "threading.py", line 982, in run
  File "workflowMain.py", line 102, in runWorkFlow
  File "conCISE.py", line 275, in __init__
  File "conCISE.py", line 253, in filterClassy
  File "pandas\core\frame.py", line 6670, in dropna
KeyError: ['superclass_annotation', 'class_annotation', 'subclass_annotation']

**Comment by Zquinlan** [comment]
Okay. [Try this one](https://github.com/Zquinlan/conCISE/releases/download/v1.21/conciseGui.exe).

I just found the error and fixed it in the code. Additionally I checked that it worked on the myBinder online interface. I don't have access to a windows computer at the moment to guarantee it will work on that OS so let me know if it doesn't :)

Sorry for the hassle.

**Comment by AndreaCa96** [comment]
Don't worry and thank you for your promptness! Unfortunately, it doesn't work yet.
pandas\io\json\_json.py:889: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
pandas\io\json\_json.py:962: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
pandas\io\json\_json.py:889: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
pandas\io\json\_json.py:962: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
pandas\io\json\_json.py:889: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
pandas\io\json\_json.py:962: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
pandas\io\json\_json.py:889: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
pandas\io\json\_json.py:962: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
pandas\core\internals\blocks.py:904: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
Exception in thread Thread-3 (runWorkFlow):
Traceback (most recent call last):
  File "threading.py", line 1045, in _bootstrap_inner
  File "threading.py", line 982, in run
  File "workflowMain.py", line 101, in runWorkFlow
  File "conCISE.py", line 278, in __init__
  File "conCISE.py", line 255, in filterClassy
  File "pandas\core\frame.py", line 6670, in dropna
KeyError: ['superclass_annotation', 'class_annotation', 'subclass_annotation']

**Comment by Zquinlan** [comment]
Shoot, okay. I am now away from my computer but I'll take another look
tonight. Im also happy to run it locally for you tonight in case it takes
me longer to deal with this bug.

**Comment by AndreaCa96** [comment]
Great, thank you for your support!

**Comment by Zquinlan** [comment]
Hi again. Would you be willing to share you GNPS job ID with me? I think its possible that the error is actually occurring from their side because I have not been able to replicate this error on Mac or PC.

Alternatively you can look at the GNPS job's library match file and look at the Classyfire superclass, class and subclass files. If I am right in my assumption, they're probably completely empty...

**Comment by AndreaCa96** [comment]
Hi, here is my finished GNPS job ID: dfd4a068ee264e438998070d4d64cda1.

Actually, I have been running other GNPS jobs for three days and none of them are finished. I guess their server is down. I checked the forum, and there are many people experiencing problems completing jobs with GNPS. 
However, with this job, if I click NPC, I get the output .csv file.

Here it is my canopus and my output files from gnps :)
[Concise.zip](https://github.com/user-attachments/files/15784595/Concise.zip)

Thanks again :)

**Comment by Zquinlan** [comment]
Hey!

I looked at the file at it appears I was correct. The error you are receiving "KeyError: ['superclass_annotation', 'class_annotation', 'subclass_annotation']" is because there is not ClassyFire information supplied from GNPS in the library match file. This has been an increasingly common problem with GNPS. They're working pretty hard to get GNPS 2 done and out to the public wherein, I hope this will be resolved but for the moment I don't think Ming has time to fix the issue. 


[libraryMatches.zip](https://github.com/user-attachments/files/15788839/libraryMatches.zip)

**Comment by Zquinlan** [comment]
I just made some updates to the NPC classifier since I was already working on the fixes and ran your job for you with NPC classifier so that you don't have to download yet another version.

It is attached below:
10 out of 11 (90.91%) networks with Library ID's found a consensus annotation
22 out of 50 (44.0%) networks with Insilico annotations found a consensus annotation
52.459999999999994% of all networks with an annotation recieved a consensus annotation

[conciseConsensus.csv.zip](https://github.com/user-attachments/files/15795730/conciseConsensus.csv.zip)

**Comment by AndreaCa96** [comment]
Ok, thank you!

So in conclusion, regarding Classifire ontologies, there is currently no solution.

For the NPC Classifire, it's fine. If I want to modify the filter for this job or run other jobs for the NPC Classifire, can I use the latest version you have uploaded (v.1.21), or is there another one?

**Comment by Zquinlan** [comment]
So theres no easy solution but there is a workaround.

What I did was:
1) Pull all the InChIKeys from your library match file and submit them to the ClassyFire website. I typically do this through [this website](https://cfb.fiehnlab.ucdavis.edu/) from the Fiehn lab at UC Davis because ClassyFires actual website cannot take more than a few requests at a time and will timeout whereas the Fiehn lab website sends the requests in batches.

2) Then I replaced the superclass, class and subclass files in the library match file from GNPS.

3) Finally, I hard coded a workaround to read in this custom library match file so concise would use it instead of the one from your library job.

I've added a to-do for myself to add a manual import option for the library match file so the workaround is available to anyone but it probably wont be added for at least a week. So to expedite everything for you,  I went ahead and did the whole workaround. In the attached .zip you will find the 'fixed' library match file, the ClassyFire export .csv from the Fiehn lab and the ConCISE consensus file using the ClassyFire ontologies. 

[ClassyFireConCISEWorkaround.zip](https://github.com/user-attachments/files/15809551/ClassyFireConCISEWorkaround.zip)

Let me know if there is anything else I can help with and thanks for using ConCISE!
